### ISSUE TITLE
Copy ID3 for first file

### ISSUE THREAD

**Issue by pynej** [dmulholland/mp3cat#1]
This tool works perfectly merging the files.  Only real issue is I then have to open up one of the original files and the new one and copy over all the ID3 details manually.  It should copy the details and possibly even the artwork from the first file.

**Comment by dmulholl** [comment]
I did think about doing this the first time round but I liked the simplicity of a blank slate. I'll certainly look at adding it as an option when I get a chance.

**Comment by pynej** [comment]
I added some code to do this: https://github.com/dmulholland/mp3cat/pull/3

**Comment by dmulholl** [comment]
I have this as an option in 2.3 under a `--tag` flag. It copies the entire existing tag in one go so images are supported. Hope it comes in useful.
