### ISSUE TITLE
Homebrew?

### ISSUE THREAD

**Issue by exside** [dmulholland/mp3cat#11]
Hi, thanks for this great tool!

Would it be possible to create a homebrew formula for your tool? Unfortunately there is another guy with a tool with the exact same name... http://tomclegg.net/mp3cat he has his version in homebrew so I mistakenly installed the wrong one =)... 

keep up the great work!

**Comment by dmulholl** [comment]
Glad you found it useful!

I did actually think about registering it with Homebrew a couple of years back but as you say the name was already taken. I'll take a look at it again when I get a chance and see what it involves.
