### ISSUE TITLE
the output mp3 audio is abnormal

### ISSUE THREAD

**Issue by lilien1010** [dmulholland/mp3cat#12]
my input audio is 
"https://sz-ht.oss-cn-shenzhen.aliyuncs.com/mvo/sz-ht/180912/5548221_ded0d71bafb5485555b04a0789f67988.mp3",
"http://ht-blog.oss-cn-hongkong.aliyuncs.com/MVP/replay/Hi%20How%20Can%20I%20Help%20You.mp3",
"https://sz-ht.oss-cn-shenzhen.aliyuncs.com/mvo/sz-ht/180912/5548221_5713acba4c719a303ffe9496a5ca0b9b.mp3",
"http://ht-blog.oss-cn-hongkong.aliyuncs.com/MVP/replay/Of%20Course%20Will%20That%20Be%20All.mp3",
"https://sz-ht.oss-cn-shenzhen.aliyuncs.com/mvo/sz-ht/180912/5548221_e3aececc611b970bc6d252903035a05d.mp3",
"http://ht-blog.oss-cn-hongkong.aliyuncs.com/MVP/replay/Alright%20I_ll%20Be%20Back%20With%20Your%20Blanket.mp3",
"https://sz-ht.oss-cn-shenzhen.aliyuncs.com/mvo/sz-ht/180912/5548221_b851e7cffab40a1f5e17d1826f5050cc.mp3"

and is output audio is stop at 15 seconds?
 https://ali-hk-cdn.hellotalk8.com/mnt/mvp/900866_a109b8fe7f0e5acb998e0817994a066b.mp3

**Comment by dmulholl** [comment]
I see the same effect although the cut-off point varies from player to player. I think the problem is that the files are a mixture of stereo and mono and that's confusing MP3 players. If you convert them all to the same format before joining them it should hopefully work.
