### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by carlosfusion** [dmulholland/mp3cat#16]
Hello im getting the follow msg:

Illegal instruction (core dumped)

Any ideas?

**Comment by dmulholl** [comment]
That's interesting, I haven't seen that before. A couple of questions: what operating system are you using, and did you run one of the precompiled binaries or build a new one using `go get`?

(If you have Go installed on your machine definitely try building a new binary using `go get github.com/dmulholl/mp3cat`. I've had Go binaries simply stop working on my own machine after the OS was updated but compiling a new binary fixed the issue.)

**Comment by carlosfusion** [comment]
i update to 3.3.0 then that error came, i download 3.1.0 again and the error was the same, so i fixed installing go and compile directly on the server machine the last version, im not sure yet why the error but its fixed building again.

thank you so much.

**Comment by dmulholl** [comment]
Glad to hear you got it working! Thanks for letting me know about the issue. I've recompiled the three release binaries (v3.3.1) with the latest version of the Go compiler which will hopefully fix the problem.

**Comment by carlosfusion** [comment]
thank you ill close the issue, have a nice day
