### ISSUE TITLE
Copy ID3 tag from any MP3 file?

### ISSUE THREAD

**Issue by tiborepcek** [dmulholland/mp3cat#17]
Is it somehow possible to copy ID3 tag of second (or any) MP3 file?

Thank you.

**Comment by dmulholl** [comment]
It isn't I'm afraid but that's an interesting idea. I'll add that feature in the next version.

**Comment by tiborepcek** [comment]
Could you, please, tell me, when the new version is out? Thanks for your time and work.

**Comment by dmulholl** [comment]
Try the latest `4.0.0.dev` version: https://darrenmulholland.com/dev/mp3cat/releases.html. You can copy the metadata from an arbitrary input file using the new `--copy-meta <n>` option. So to copy the metadata from the second file use:

    --copy-meta 2

**Comment by tiborepcek** [comment]
Great, it works! Many thanks! :)

**Comment by dmulholl** [comment]
Happy to help, thanks for the feedback!
