### ISSUE TITLE
Constant bitrate and position information in the headers

### ISSUE THREAD

**Issue by tiborepcek** [dmulholland/mp3cat#18]
In this [issue for AntennaPod](https://github.com/AntennaPod/AntennaPod/issues/3776), i am asking for help with MP3 file joined with MP3Cat.

One of [developer answered](https://github.com/AntennaPod/AntennaPod/issues/3776#issuecomment-578407991): "The problem is that MP3Cat seems to use a variable bitrate and also does not include position information in the headers."

Can you do something about it?

Thank you.

**Comment by dmulholl** [comment]
If you use variable bitrate input files the output file will also be variable bitrate. The only way to transform VBR input into CBR output is to re-encode the files using something like [ffmpeg](https://www.ffmpeg.org). 

Adding position information to the headers is beyond the scope of this project I'm afraid. I'd recommend using CBR files instead if you have the option.

**Comment by tiborepcek** [comment]
I understand. In this case, i wanted avoid to use ffmpeg and was seeking something smaller in size (62 MB ffmpeg.exe vs. 2,5 MB mp3cat.exe) and functionality. But now i see, that it is not so easy task. :)

Anyhow, thank you again for your work. I really appreciate it.
