### ISSUE TITLE
Recompile

### ISSUE THREAD

**Issue by pynej** [dmulholland/mp3cat#2]
You also need to update the binaries compiled with go 1.8 to prevent some race conditions.

**Comment by dmulholl** [comment]
Don't understand this I'm afraid - can you elaborate?

**Comment by pynej** [comment]
The binary version you have on your site at http://mulholland.xyz/dev/mp3cat/ was bailed with an over version of go.  On my system this binary would randomly fail when processing audio files.  Recompiling the code on go 1.8 produced a binary that works.  Not any actual changes in the code though.

**Comment by dmulholl** [comment]
Thanks for letting me know - I didn't realise this was an issue! Is this a known bug with older versions of the Go compiler?

**Comment by pynej** [comment]
Yes, exactly.

**Comment by dmulholl** [comment]
Done. Thanks for the heads up.
