### ISSUE TITLE
Cannot compile because of missing files

### ISSUE THREAD

**Issue by Kilowatt-W** [dmulholland/mp3cat#20]
Hello, 
i would like to extend the features with some vraiables and placeholders for outputfilemgmt and so on, hope this project is still alive.

where can i get the missing crypto ssh lib ?

Greetings from Austria

**Comment by dmulholl** [comment]
Hi, that's interesting, I've just checked and the `golang.org/x/crypto/ssh/terminal` package import is failing to download automatically for me too.

Looks like there's a workaround. I ran:

    go get -u golang.org/x/crypto/ssh/terminal

on the command line and it installed the package without a problem and then `mp3cat` was able to build.

**Comment by Kilowatt-W** [comment]
HI thx yes that did the trick for me to,

finished my first work for making some music files for my child :-)

**Comment by dmulholl** [comment]
That's great, glad I could help :)
