### ISSUE TITLE
ID3v2 chapter support

### ISSUE THREAD

**Issue by uffsalot** [dmulholland/mp3cat#25]
Would it be possible to implement [id3v2 chapter](https://id3.org/id3v2-chapters-1.0) support and set them based on the timestamps and names/tags of the individual mp3 files?
i use mp3cat to combine split audiobooks into one file to make it available to my podcast client with [DirCaster](https://dircaster.org/index.html). Chapter support would be a great addition to this setup.

Thank you for this nice piece of software.

**Comment by dmulholl** [comment]
Hi @uffsalot, that was my original use-case too :)

That does sound like an interesting idea but I'm not going to add any extra features to `mp3cat` as my plan is to keep it as simple as possible. There's an existing fork called `mp3binder` (https://github.com/crra/mp3binder) that has a lot of extra functionality -- you could try suggesting the idea there.
