### ISSUE TITLE
--dir parameter on Windows won't find any files to merge

### ISSUE THREAD

**Issue by creopard** [dmulholland/mp3cat#6]
I tried to merge several files in a directoy with Windows 7, but it just results in the error message
"Error: no files found."

tried multiple variations:
- mp3cat --dir D:\files
- mp3cat --dir D:/files
- mp3cat --dir D:\files\
- mp3cat --dir D:/files/

but none of it succeded.
What's the correct syntax for Windows OS systems?

**Comment by dmulholl** [comment]
That's odd, either the first or second variants should work fine. Does it work if you use command line globbing instead, i.e.

    mp3cat D:\files\*.mp3

The end result should be exactly the same.

**Comment by creopard** [comment]
Unfortunately, adding the extension like your example doesn't make a difference.

**Comment by dmulholl** [comment]
Apparently the Windows command line doesn't have built-in support for globbing - I didn't know that.

I just checked and the `--dir` command is working fine for me on Windows 7. I used it as:

    mp3cat --dir D:\files

and it found and merged a directory of `.mp3` files. I don't know why it isn't working for you but if you figure it out please do let me know!

**Comment by creopard** [comment]
I found the error:
My testfiles were named as follows:
- filename1.MP3
- filename2.MP3

renaming the extension to lowercase like:
- filename1.mp3
- filename2.mp3
did the trick. Now it's working :)

Thanks for the support anyways!

**Comment by dmulholl** [comment]
Perfect :) Thanks for letting me know!

**Comment by ohadschn** [comment]
@dmulholland IMHO `mp3cat` should ignore the case of the extension... so `mp3`, `MP3`, `Mp3` etc. should all work.

**Comment by dmulholl** [comment]
I agree @ohadschn. Done on master - I'll cut a 3.1 release when I get a chance.
