### ISSUE TITLE
Merge files for audio captcha, but get silent sound.

### ISSUE THREAD

**Issue by ycrao** [dmulholland/mp3cat#7]
Hi ,

Question as the title says.

I run `mp3cat` on my MacBook. I will  email my source and script files to you later.

Hope you can help me!

**Comment by dmulholl** [comment]
Hi Rao. Some of your files are single-channel with a sampling rate of 44.1kHz while others are dual-channel with a sampling rate of 24kHz. I think most MP3 players will choke if you mix such different formats up in a single file. You could try converting them all to a single format before merging them.
