### ISSUE TITLE
Why not make merge function an exported one

### ISSUE THREAD

**Issue by davyzhang** [dmulholland/mp3cat#8]
I think this will the library more useful when people try to embed this library into their code

**Comment by dmulholl** [comment]
It's actually already set up as an executable front-end and a library back-end - here's a link to the library:

https://github.com/dmulholland/mp3lib

**Comment by davyzhang** [comment]
Thanks for these wonderful libs you've created, which help me a lot on my current project.

**Comment by dmulholl** [comment]
You're very welcome - great to hear you're finding them useful!
